nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4250']
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['http://localhost:4250']
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            allow_credentials: true